### ISSUE TITLE
Repo has no Licence

### ISSUE THREAD

**Issue by melvincarvalho** [Darcy-Social/ibex#2]
Thanks for an awsome project / app!

I was wondering what License the darcy team would like to use, if any

Are you interested in contributors, at this point?

**Comment by JollyOrc** [comment]
good point - after a brief talk with the team, I've added a CC-BY-NC license to the repo. If someone needs one for commercial use, we'll probably happy to grant that too on a case by case basis.

And yes, of course: Contributions are very welcome!
