### ISSUE TITLE
Missing comments due to timestamp difference

### ISSUE THREAD

**Issue by angelo-v** [Darcy-Social/ibex#4]
I created a comment that got stored as `2020-01-10T11.20.34.579Z.comment` to my Pod.

BUT: The respective pingback file was named with a difference of one millisecond: `DARCY_angelo.veltens.org_2020-01-10T11.20.34.580Z_comment`.

This leads to the comment not showing up. The content of the pingback file is correct, so as a workarroudn I just renamed it and the comment shows up again.

**Comment by tsojcanth** [comment]
Testing fix...

**Comment by tsojcanth** [comment]
slug is now created one time for both comment and pingback. Waiting for user feedback.

**Comment by JollyOrc** [comment]
> slug is now created, then used for both comment and pingback. Waiting for user feedback.
from my point of view, things look fine, but that might not be enough I guess?

**Comment by tsojcanth** [comment]
@angelo-v the bug has been fixed and deployed live. Test passed.
